### ISSUE TITLE
Fix background image to span the whole background and not repeat

### ISSUE THREAD

**Issue by rodneystrong** [EditLLC/client-solista#2]
Depending on what size the browser is, the bg image of roberto shows a repeat. 

Make it so the full size image resizes and crops itself intelligently. 

I think the CSS is background-size: cover or contain

Due date: Sat 6-20-15

**Comment by purplyrocky** [comment]
I've already done a background-repeat: none in CSS but i haven't pushed yet. currently trying to fix the size and have it fixed

**Comment by purplyrocky** [comment]
done 096a5f1c8780f368bc886c4d55971d7b7063d337
