### ISSUE TITLE
Implement playlist feature

### ISSUE THREAD

**Issue by rodneystrong** [EditLLC/client-solista#3]
and push that feature to LIVE!!   FTP yo. ya heeeard.

due date: Tue 6-23-15

**Comment by purplyrocky** [comment]
I got the playlist updated, I just want to try and fix that "repeat" button and maybe change the background color before closing this issue.

**Comment by rodneystrong** [comment]
Oh nice!! Good job good job! 

I'll make a new issue for the repeat button; don't worry about it. This is good as closed. I'll create the issue for the button.

**Comment by purplyrocky** [comment]
Got it.
