### ISSUE TITLE
Fix 'repeat' button

### ISSUE THREAD

**Issue by rodneystrong** [EditLLC/client-solista#6]
Wat is goin on... why is the repeat button hangin out on Gilligan's island by itself?  o_O) 

Due date: Wed 6-24-15

**Comment by purplyrocky** [comment]
@rodneystrong 
WHAT THE WHAT?! The repeat button doesn't even work on the demo player:
http://www.jplayer.org/latest/demo-02/

:(

**Comment by rodneystrong** [comment]
Wait a minute, the repeat button IS working. I could be wrong, but I think you're assuming the repeat button is supposed to repeat single tracks, but in reality, the repeat button is repeating the whole playlist. 

The way you know this is if you listen to the last song in the playlist and then it starts back at the first song in the playlist. Try it, it works like that.

**Comment by rodneystrong** [comment]
And oh yea, good job on solving this!

**Comment by purplyrocky** [comment]
yeah i thought the repeat button would REPEAT the song hahaha stuuupid meeeee .___.
