### ISSUE TITLE
Fix jPlayer display

### ISSUE THREAD

**Issue by rodneystrong** [EditLLC/client-solista#7]
I may have messed up your jPlayer playlist on my latest pushes. :( 

Sorry about that. Since you're most familiar with your code, could you go through and fix the playlist please? 

I plan to email Roberto Lopez tonight or tomorrow with the mariachisolista.com link for him to review and note anything.

**Comment by purplyrocky** [comment]
I'm not sure how but I got the player to display the playlist again.
