### ISSUE TITLE
Update mariachisolista.com

### ISSUE THREAD

**Issue by rodneystrong** [EditLLC/client-solista#8]
When all changes are correct, please upload them to the mariachisolista.com FTP.

By the way, the code for the jPlayer playlist on mariachisolista.com seems to be correct (except for the repeat button). Maybe you can cherrypick which pieces of code will work for the gh-pages and master branch? I dont know, whichever way helps you complete it faster. 

Due date: 
7-6-15  11pm

**Comment by purplyrocky** [comment]
That damn repeat button! I also noticed it wasn't working. I have to find the original repeat button code and try to replace it with the one that works. I will FTP and close this issue when I fix

**Comment by purplyrocky** [comment]
Gonna go ahead and FTP everything else and kep this issue open, I suppose:
https://github.com/EditLLC/client-solista/issues/6
